name: release-please

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}   # allow manual runs

permissions:
  contents: write         # needed to push release commits & create releases
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          # For a single Maven project in repo root:
          release-type: maven
          manifest-file: ".release-please-manifest.json"
          config-file: "release-please-config.json"
